import { Categories } from '~/types';

const KNOWN_CATEGORIES_MAP = {
  carrefour: Categories.GROCERIES,
  'albert heijn': Categories.GROCERIES,
  jumbo: Categories.GROCERIES,
  dirk: Categories.GROCERIES,
  lidl: Categories.GROCERIES,
  action: Categories.GROCERIES,
  spar: Categories.GROCERIES,
  vomar: Categories.GROCERIES,
  supermarket: Categories.GROCERIES,
  market: Categories.GROCERIES,
  grocery: Categories.GROCERIES,
  food: Categories.GROCERIES,
  fresh: Categories.GROCERIES,
  organic: Categories.GROCERIES,
  bio: Categories.GROCERIES,
  booking: Categories.TRAVEL,
  airbnb: Categories.TRAVEL,
  airline: Categories.TRAVEL,
  klook: Categories.TRAVEL,
  air: Categories.TRAVEL,
  hotel: Categories.TRAVEL,
  hostel: Categories.TRAVEL,
  flight: Categories.TRAVEL,
  'train ticket': Categories.TRAVEL,
  visa: Categories.TRAVEL,
  passport: Categories.TRAVEL,
  luggage: Categories.TRAVEL,
  tourist: Categories.TRAVEL,
  trip: Categories.TRAVEL,
  vacation: Categories.TRAVEL,
  holiday: Categories.TRAVEL,
  expedia: Categories.TRAVEL,
  trivago: Categories.TRAVEL,
  transavia: Categories.TRAVEL,
  klm: Categories.TRAVEL,
  easyjet: Categories.TRAVEL,
  uber: Categories.TRANSPORT,
  ovchipkaart: Categories.TRANSPORT,
  ovpay: Categories.TRANSPORT,
  ns: Categories.TRANSPORT,
  grab: Categories.TRANSPORT,
  taxi: Categories.TRANSPORT,
  bus: Categories.TRANSPORT,
  train: Categories.TRANSPORT,
  metro: Categories.TRANSPORT,
  parking: Categories.TRANSPORT,
  fuel: Categories.TRANSPORT,
  petrol: Categories.TRANSPORT,
  'gas station': Categories.TRANSPORT,
  shell: Categories.TRANSPORT,
  bp: Categories.TRANSPORT,
  esso: Categories.TRANSPORT,
  'car rental': Categories.TRANSPORT,
  bike: Categories.TRANSPORT,
  scooter: Categories.TRANSPORT,
  toll: Categories.TRANSPORT,
  cafe: Categories.RESTAURANTS_AND_COFFEE,
  coffee: Categories.RESTAURANTS_AND_COFFEE,
  restaurant: Categories.RESTAURANTS_AND_COFFEE,
  bar: Categories.RESTAURANTS_AND_COFFEE,
  doner: Categories.RESTAURANTS_AND_COFFEE,
  pizza: Categories.RESTAURANTS_AND_COFFEE,
  burger: Categories.RESTAURANTS_AND_COFFEE,
  mcdonald: Categories.RESTAURANTS_AND_COFFEE,
  kfc: Categories.RESTAURANTS_AND_COFFEE,
  starbucks: Categories.RESTAURANTS_AND_COFFEE,
  domino: Categories.RESTAURANTS_AND_COFFEE,
  subway: Categories.RESTAURANTS_AND_COFFEE,
  bakery: Categories.RESTAURANTS_AND_COFFEE,
  pub: Categories.RESTAURANTS_AND_COFFEE,
  bistro: Categories.RESTAURANTS_AND_COFFEE,
  tavern: Categories.RESTAURANTS_AND_COFFEE,
  grill: Categories.RESTAURANTS_AND_COFFEE,
  delivery: Categories.RESTAURANTS_AND_COFFEE,
  takeaway: Categories.RESTAURANTS_AND_COFFEE,
  'food delivery': Categories.RESTAURANTS_AND_COFFEE,
  thuisbezorgd: Categories.RESTAURANTS_AND_COFFEE,
  pathe: Categories.ENTERTAINMENT,
  crunchyroll: Categories.ENTERTAINMENT,
  cinema: Categories.ENTERTAINMENT,
  movie: Categories.ENTERTAINMENT,
  netflix: Categories.ENTERTAINMENT,
  youtube: Categories.ENTERTAINMENT,
  spotify: Categories.ENTERTAINMENT,
  disney: Categories.ENTERTAINMENT,
  gaming: Categories.ENTERTAINMENT,
  steam: Categories.ENTERTAINMENT,
  playstation: Categories.ENTERTAINMENT,
  xbox: Categories.ENTERTAINMENT,
  theater: Categories.ENTERTAINMENT,
  concert: Categories.ENTERTAINMENT,
  museum: Categories.ENTERTAINMENT,
  zoo: Categories.ENTERTAINMENT,
  park: Categories.ENTERTAINMENT,
  kruidvat: Categories.HEALTH,
  etos: Categories.HEALTH,
  'holland&barrett': Categories.HEALTH,
  pharmacy: Categories.HEALTH,
  doctor: Categories.HEALTH,
  dentist: Categories.HEALTH,
  hospital: Categories.HEALTH,
  clinic: Categories.HEALTH,
  medicine: Categories.HEALTH,
  vitamin: Categories.HEALTH,
  fitness: Categories.HEALTH,
  gym: Categories.HEALTH,
  massage: Categories.HEALTH,
  therapy: Categories.HEALTH,
  hema: Categories.SHOPPING,
  bol: Categories.SHOPPING,
  amazon: Categories.SHOPPING,
  'h&m': Categories.SHOPPING,
  gamma: Categories.SHOPPING,
  clothing: Categories.SHOPPING,
  shoes: Categories.SHOPPING,
  electronics: Categories.SHOPPING,
  tech: Categories.SHOPPING,
  apple: Categories.SHOPPING,
  samsung: Categories.SHOPPING,
  zara: Categories.SHOPPING,
  nike: Categories.SHOPPING,
  adidas: Categories.SHOPPING,
  'online shop': Categories.SHOPPING,
  webshop: Categories.SHOPPING,
  waternet: Categories.HOUSEHOLD,
  'budget energie': Categories.HOUSEHOLD,
  ikea: Categories.HOUSEHOLD,
  'basic package': Categories.HOUSEHOLD,
  utilities: Categories.HOUSEHOLD,
  electricity: Categories.HOUSEHOLD,
  water: Categories.HOUSEHOLD,
  internet: Categories.HOUSEHOLD,
  phone: Categories.HOUSEHOLD,
  insurance: Categories.HOUSEHOLD,
  cleaning: Categories.HOUSEHOLD,
  laundry: Categories.HOUSEHOLD,
  repair: Categories.HOUSEHOLD,
  maintenance: Categories.HOUSEHOLD,
};

const knownCategories = Object.keys(
  KNOWN_CATEGORIES_MAP
) as (keyof typeof KNOWN_CATEGORIES_MAP)[];

export const getKnownCategory = (description = '') => {
  const lowerCaseDescription = description.toLowerCase();

  const categoryKey = knownCategories.find(category =>
    lowerCaseDescription.includes(category)
  );

  if (!categoryKey) return undefined;

  return KNOWN_CATEGORIES_MAP[categoryKey];
};
